# config.yaml

project:
  name: Road Extraction with UNet++
  output_dir: outputs/
  save_model: true

data:
  train_images_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\train
  train_masks_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\train
  val_images_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\valid
  val_masks_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\valid
  image_size: 512
  batch_size: 4
  num_workers: 4
  augmentations: true

model:
  architecture: unetplusplus
  encoder_name: efficientnet-b4
  encoder_weights: imagenet
  activation: sigmoid
  in_channels: 3
  classes: 1

train:
  epochs: 50
  learning_rate: 1e-4
  weight_decay: 1e-5
  early_stopping_patience: 10
  checkpoint_path: checkpoints/best_model.pth
  log_interval: 5
  seed: 42
  resume_training: false
