# config.yaml

project:
  name: Road Extraction with DeepLabV3+
  output_dir: outputs/
  save_model: true

data:
  train_images_dir: data/train/images/
  train_masks_dir: data/train/masks/
  val_images_dir: data/val/images/
  val_masks_dir: data/val/masks/
  image_size: 256
  batch_size: 8
  num_workers: 4
  augmentations: true

model:
  architecture: deeplabv3plus
  encoder_name: resnet34
  encoder_weights: imagenet
  activation: sigmoid
  in_channels: 3
  classes: 1

train:
  epochs: 50
  learning_rate: 0.0001
  early_stopping_patience: 10
  checkpoint_path: checkpoints/best_model.pth
  log_interval: 5
  seed: 42
