# config.yaml

project:
  name: Road Extraction with DeepLabV3+
  output_dir: outputs/
  save_model: true

data:
  train_images_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\train
  train_masks_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\train
  val_images_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\valid
  val_masks_dir: D:\naki\Projects\IVP\roadnet_minimal\data\archive\valid
  image_size: 256
  batch_size: 8
  num_workers: 4
  augmentations: true

model:
  architecture: deeplabv3plus
  encoder_name: resnet34
  encoder_weights: imagenet
  activation: sigmoid
  in_channels: 3
  classes: 1

train:
  epochs: 7
  learning_rate: 0.00008
  weight_decay: 0.0001 # Added weight decay
  early_stopping_patience: 10
  checkpoint_path: checkpoints/best_model.pth
  log_interval: 5
  seed: 42
